Resources:
  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: key
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: keyindex
          KeySchema:
            - AttributeName: key
              KeyType: HASH
            - AttributeName: slug
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      KeySchema:
        - AttributeName: slug
          KeyType: HASH

  ReportsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: slug
          AttributeType: S
        - AttributeName: reportkey
          AttributeType: S
      KeySchema:
        - AttributeName: slug
          KeyType: HASH
        - AttributeName: reportkey
          KeyType: RANGE
