Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path:
      AssumeRolePolicyDocument:
      Policies:
        - PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "*"
                Resource: "*"
