Resources:
  ClickEventsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1
  ClickEventsDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: KinesisStreamAsSource
      KinesisStreamSourceConfiguration:
        KinesisStreamArn: !GetAtt ClickEventsStream.Arn
        RoleARN: !GetAtt DeliveryStreamRole.Arn
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt ClickEventsBucket.Arn
        RoleArn: !GetAtt DeliveryStreamRole.Arn
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt DeliveryStreamProcessorLambdaFunction.Arn
