swagger: "2.0"
info:
  description: "LinkShrink"
  version: "1.0.0"
  title: "LinkShrink"
host: "test.com"
basePath: "/"
schemes:
  - "https"
  - "http"
paths:
  /{slug}:
    get:
      summary: "Redirect to a link"
      description: "Gets the link and redirects the browser."
      operationId: "getLink"
      produces:
        - "application/html"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link to return"
          required: true
          type: "string"
      responses:
        "301":
          description: "Success, redirect to destination"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"

  /link:
    post:
      tags:
        - "link"
      summary: "Create link"
      description: "Create a shrink link."
      operationId: "createLink"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CreateLinkRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateLinkResponse"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /link/{slug}:
    get:
      tags:
        - "link"
      summary: "Get link metadata"
      description: "Returns metadata and information about the link."
      operationId: "getLinkInfo"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetLinkInfoResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  CreateLinkRequest:
    type: "object"
    properties:
      link:
        type: "string"
        required: true
      clicks:
        type: "boolean"
        required: true
      expires:
        type: "string"
        format: "date-time"
        required: true
      slug:
        type: "string"
        required: false
  CreateLinkResponse:
    type: "object"
    properties:
      slug:
        type: "string"
  GetLinkInfoResponse:
    type: "object"
    properties:
      slug:
        type: string
      link:
        type: string
      key:
        type: string
      clicks:
        type: boolean
      expires:
        type: string
        format: date-time
      created:
        type: string
        format: date-time

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
