swagger: "2.0"
info:
  description: "LinkShrink"
  version: "1.0.0"
  title: "LinkShrink"
host: "test.com"
basePath: "/"
schemes:
  - "https"
  - "http"
paths:
  /{slug}:
    get:
      summary: "Redirect to a link"
      description: "Gets the link and redirects the browser."
      operationId: "getLink"
      produces:
        - "application/html"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link to return"
          required: true
          type: "string"
          format: "ksuid"
      responses:
        "301":
          description: "Success, redirect to destination"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"

  /link:
    post:
      tags:
        - "link"
      summary: "Create link"
      description: "Create a shrink link."
      operationId: "createLink"
      produces:
        - "application/json"
      parameters:
        - in: body
          name: body
          schema:
            $ref: "#/definitions/CreateLinkRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateLinkResponse"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /link/{slug}:
    get:
      tags:
        - "link"
      summary: "Get link metadata"
      description: "Returns metadata and information about the link."
      operationId: "getLinkInfo"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetLinkInfoResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /link/{slug}/stats:
    get:
      tags:
        - "link"
      summary: "Get link statistics"
      description: "Returns statistics about the link."
      operationId: "getLinkStats"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetLinkStatsResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /report/{slug}:
    post:
      tags:
        - "report"
      summary: "Start report workflow"
      description: "Start workflow to generate a report for a link."
      operationId: "createLinkReport"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link"
          required: true
          type: "string"
        - name: body
          in: body
          schema:
            $ref: "#/definitions/CreateLinkReportRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateLinkReportResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /report/{slug}/{reportkey}:
    get:
      tags:
        - "report"
      summary: "Get report information"
      description: "Get metadata and status of a link report."
      operationId: "getLinkReportStatus"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link"
          required: true
          type: "string"
        - name: "reportkey"
          in: "path"
          description: "Key of the report"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetLinkReportStatusResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

  /report/{slug}/{reportkey}/link:
    get:
      tags:
        - "report"
      summary: "Get report download"
      description: "Get presigned S3 url to download report."
      operationId: "getLinkReport"
      produces:
        - "application/json"
      parameters:
        - name: "slug"
          in: "path"
          description: "Slug of the link"
          required: true
          type: "string"
        - name: "reportkey"
          in: "path"
          description: "Key of the report"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetLinkReportResponse"
        "404":
          description: "Link doesn't exist"
        "401":
          description: "Unauthorized for this link"
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
definitions:
  CreateLinkRequest:
    type: "object"
    properties:
      link:
        type: "string"
      clicks:
        type: "boolean"
        default: true
      expires:
        type: "string"
        format: "date-time"
  CreateLinkResponse:
    type: "object"
    properties:
      slug:
        type: "string"
  GetLinkInfoResponse:
    type: "object"
    properties:
      slug:
        type: string
      link:
        type: string
      key:
        type: string
      clicks:
        type: boolean
      expires:
        type: string
        format: date-time
      created:
        type: string
        format: date-time
  GetLinkStatsResponse:
    type: "object"
    properties:
      slug:
        type: string
      count:
        type: integer
        format: int64
        minimum: 0
  CreateLinkReportRequest:
    type: "object"
    properties:
      start:
        type: string
        format: date-time
      stop:
        type: string
        format: date-time
  CreateLinkReportResponse:
    type: "object"
    properties:
      key:
        type: string
      reportkey:
        type: string
  GetLinkReportStatusResponse:
    type: "object"
    properties:
      key:
        type: string
      reportkey:
        type: string
      slug:
        type: string
      status:
        type: string
  GetLinkReportResponse:
    type: "object"
    properties:
      url:
        type: string

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
